apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-4-demo-app
  labels:
    app: team-4-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: team-4-demo-app
  template:
    metadata:
      labels:
        app: team-4-demo-app
    spec:
      containers:
        - name: team-4-demo-app
          image: 980637429038.dkr.ecr.ap-south-1.amazonaws.com/team-4-demo-app:T4
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: team-4-demo-app-service
  labels:
    app: team-4-demo-app
spec:
  type: LoadBalancer
  selector:
    app: team-4-demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
